### ISSUE TITLE
ci: travis-ci dry-run optimizations

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/openstack-helm#187]
1) Suggest dry-run logic is put into make so developers can run it locally:

`make dry-run`

2) Suggest dry-run logic pipes output: `helm .... 2>&1 > /tmp/dry-run-output.log` for each chart and simply validates that `helm --dry-run` exited with 0.  If it is !=0 then it does a `cat /tmp/dry-run-output.log`.  This solves out huge output issue as charts rendering fine are not of interest.

3) We should do a grep on `/tmp/dry-run-output.log` to look for `'gotpl'` - this surfaces when there is a pipeline issue but does not result in a `helm ... --dry-run` error or exit status of non-zero.  To test, edit a pipeline, such as the `init-dep-check` in a random chart, change it to a non-existent value, and run it through dry-run.  You will see lines in the output such as `template: .... 'gotpl' ... error` but it will not fail the dry-run.

**Comment by wilkers-steve** [comment]
@alanmeadows Sounds good.  These changes shouldn't be difficult, and I can work on getting these in over the next day or two

**Comment by nadeemanwar** [comment]
@alanmeadows what you do when you found the error like 'gotpl', fail the build or just print it in the log?

Running helm install --dry-run --debug on maas-0.1.0.tgz
2017/02/16 03:03:06 storage.go:37: Getting release "boisterous-chipmunk" (v1) from storage
2017/02/16 03:03:06 release_server.go:826: Dry run for boisterous-chipmunk
No Error found for dry run checking for gotpl
    template: no template "helm_toolkit.template" associated with template "gotpl"
    template: no template "dep_check_init_cont" associated with template "gotpl"

**Comment by alanmeadows** [comment]
This is a failed build when this occurs.  If we find this, there is no way the template will have been rendered correctly.

**Comment by nadeemanwar** [comment]
@alanmeadows  I updated the script to fail the build when 'gotpl' is found the log. Now the build is failing on this one. How to fix it :-)  This is the last log from my testing which is to fix the part 2 and 3 of the issue.
https://travis-ci.org/nadeemanwar/openstack-helm/builds/202304181

**Comment by nadeemanwar** [comment]
I added a check to see certain phrases in the output log because even when the dry-run install is successful we can still see errors in the log. I added a erros.list file in repo where we can define the phrases which we should search in the output log after the installation of chart and if we find something, fail the build.

Currently it is looking for ‘gotpl’ word and it was found in 4 different logs and that is why we see 4 failed log in the link above.
I need some help to understand, if that is really an issue or false positive.

-	In glance, I see this
ceph.client.admin.keyring: |+
    [client.admin]
        key =template: no template "secrets/ceph-client-key" associated with template "gotpl"

-	In Nova, I see this 
ceph.client.cinder.keyring.yaml: |+
    template: no template "nova/templates/etc/_ceph.client.cinder.keyring.yaml.tpl" associated with template "gotpl"

-	In Cinder, I see this
rbd_secret_uuid =template: no template "secrets/ceph-client-key" associated with template "gotpl"

and

ceph.client.admin.keyring: |+
    [client.admin]
        key =template: no template "secrets/ceph-client-key" associated with template "gotpl"


-	In Maas, I see this
secret: |
    template: no template "helm_toolkit.template" associated with template "gotpl"
    maas-region-controller.conf: |
    template: no template "helm_toolkit.template" associated with template "gotpl"

and

maas-region-controller.postinst: |
    template: no template "helm_toolkit.template" associated with template "gotpl"
  import-boot-resources.sh: |
    template: no template "helm_toolkit.template" associated with template "gotpl"
  job-readiness.sh: |
    template: no template "helm_toolkit.template" associated with template "gotpl"
  register-rack-controller.sh: |
    template: no template "helm_toolkit.template" associated with template "gotpl"

and 

annotations:
        pod.beta.kubernetes.io/init-containers: '[
          template: no template "dep_check_init_cont" associated with template "gotpl"



I see the same lines in the current att-comdev/openstack-helm travis-ci build but because we don’t check them so build is passing.

So I wanted to know, if we need to check that or if it is some kind of dependency issue?

**Comment by wilkers-steve** [comment]
@nadeemanwar when's the last time you rebased?  Some of these errors (the maas bits in particular) are due to a previous error that was fixed.  "helm_toolkit.template" is "helm-toolkit.template" in the fixed version.  I'd rebase and rerun the jobs

**Comment by nadeemanwar** [comment]
Thank Steve. I pull the new changes and yes the maas issues disappeared but other 3 I am still getting them.

**Comment by js5175** [comment]
@nadeemanwar 
1) Can we update it so that for the openstack components this change doesn't err out, rather it can log it as a warning for now?
2) Submit this as a WIP PR so everyone can take a look (and we can see the travis execution).

**Comment by wilkers-steve** [comment]
@nadeemanwar The nova issue is related to a template declared for the nova etc configmap.  I've filed an issue here: https://github.com/att-comdev/openstack-helm/issues/230.  Good catch.

The other issues are looking for secrets that don't exist because we haven't generated them yet.  We can either do one of two things:  We can try to generate the secrets before we run `helm install foo --dry-run --debug` or we can check the output and ignore any template warnings raised related to secrets.

**Comment by nadeemanwar** [comment]
I added the warning log phrases and warning log and created the WIP PR.

**Comment by v1k0d3n** [comment]
I'm not really sure we need this anymore at least in consideration of Travis. going to close and track.
